### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by Suizer98** [weacast/weacast-grib2json#18]
Hi, appreciate your works on making this compatible with Docker, ever think of containerise this? I forked your repository and made a docker-compose.yml: https://github.com/Suizer98/weacast-grib2json/blob/master/docker-compose.yml

So maybe some ppl can make use of container or even turn it into a small api.

**Comment by claustres** [comment]
Sorry for the late reply, this repository has been migrated into the mono repository https://github.com/weacast/weacast/tree/master/packages/grib2json. A dockerfile do exists and although we do not publish it you should be able to use it as stated in the [README](https://github.com/weacast/weacast/blob/master/packages/grib2json/README.md#using-the-docker-container).

Turn it into an API should be possible as well because it can already being integrated as a [nodejs module](https://github.com/weacast/weacast/blob/master/packages/grib2json/README.md#as-module) although a command-line is used under the hood.
